# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger:
- main

pool:
  vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
steps:
    -uses: actions/checkout@v3

    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}} 
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
    - name: docker build backend
      # registry: docker.io
      run: |
        docker build ./backend -t omaranwarorbispay/backend-vidly
        docker push omaranwarorbispay/backend-vidly
    - name: docker build frontend
      run: |
        docker build ./frontend -t omaranwarorbispay/frontend-vidly
        docker push omaranwarorbispay/frontend-vidly