# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name : Docker-CI-GitHub(docker-test)-frontend-image-to-DockerHub

trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest


variables:
  ImageName: 'omaranwarorbispay/azure-vidly-test-frontend:$(Build.BuildId)'


stages:
  - stage: Build
    displayName: Build and push image to Docker Hub
    jobs:
      - job: DockerImage
        displayName: Build and push Docker Image
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'Docker Hub-omaranwarorbispay'
              repository: 'omaranwarorbispay / azure-vidly-test-frontend'
              command: 'buildAndPush'
              Dockerfile: 'frontend/Dockerfile'
              tags: $(Build.BuildId)
              # buildContext: 


# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
