name: vidly docker

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  backend_image_name: backend-vidly
  frontend_image_name: frontend-vidly

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    # - name: docker login
    #   env:
    #     DOCKER_USER: ${{secrets.DOCKER_USERNAME}} 
    #     DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

    #   run: |
    #     echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
    - name: backend docker image build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./backend/Dockerfile
        push: true
        tags:  |
          ${{ secrets.DOCKER_USERNAME }}/$backend_image_name

    - name: frontend docker image build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./frontend/Dockerfile
        push: true
        tags:  |
          ${{ secrets.DOCKER_USERNAME }}/$frontend_image_name



    # - name: docker build backend
    #   # registry: docker.io
    #   run: |
    #     docker build ./backend -t omaranwarorbispay/backend-vidly
    #     docker push omaranwarorbispay/backend-vidly

    # - name: docker build frontend
    #   run: |
    #     docker build ./frontend -t omaranwarorbispay/frontend-vidly
    #     docker push omaranwarorbispay/frontend-vidly

    # - name: Docker Compose Action
    #   uses: isbang/compose-action@v1.4.1
    #   with:
    #     compose-file: "docker-compose.yml"
