name: vidly docker

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME}} 
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: docker build backend
      run: |
        docker build ./backend -t omaranwarorbispay/backend
    
    - name: docker build frontend
      run: |
        docker build ./frontend -t omaranwarorbispay/frontend
