name: vidly docker

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: docker build backend
      run: |
        docker build ./backend -t omaranwarorbispay/backend
    - name: docker build frontend
      run: |
        docker build ./frontend -t omaranwarorbispay/frontend
